name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.0.0-dev.9
homepage: https://github.com/simolus3/web3dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # code generation for contracts, shouldn't be imported outside of lib/src/builder/
  build: ^1.6.3
  build_config: ^0.4.6
  dart_style: ^1.3.14
  code_builder: ^3.7.0


  pointycastle: ^2.0.1
  convert: ^3.0.0
  meta: ^1.1.0
  http: ^0.13.0
  uuid: ^3.0.1
  isolate: ^2.0.0
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  json_rpc_2: ^2.1.0
  collection: ^1.14.11

dev_dependencies:
  build_runner: ^1.11.0
  web_socket_channel: ^2.0.0
  path: ^1.6.2
  test: ^1.9.0
  mockito: ^5.0.0
  coverage: ^1.0.1

dependency_overrides:
  # todo: Remove after https://github.com/dart-lang/build/issues/3024
  web_socket_channel: ^2.0.0
